### ISSUE TITLE
libblitz package unavailable on Ubuntu 17.10 - update user guide

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/LNAplusplus#1]
```
E: Package 'libblitz0-dev' has no installation candidate
E: Unable to locate package libblitz0ldbl
E: Unable to locate package libblitz-doc
```

**Comment by JanHasenauer** [comment]
please do not change the documentation in the moment. i'm currently updating the whole thing.

**Comment by dweindl** [comment]
I'd propose changing the user guide to markdown later on to allow tracking changes in git.

**Comment by JanHasenauer** [comment]
I would have prepared a single tex file, including the math background.

**Comment by dweindl** [comment]
Or that, but no docx.

**Comment by JanHasenauer** [comment]
The file would be uploaded in a separate folder including the corresponding images.

**Comment by JanHasenauer** [comment]
Agreed
