### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by JanHasenauer** [ICB-DCM/LNAplusplus#13]
For all the models I get warnings of the type

Building with 'Xcode with Clang'.
/usr/bin/xcrun -sdk macosx10.13 clang -c -DTARGET_API_VERSION=700  -DUSE_MEX_CMD   -DMATLAB_MEX_FILE -Ichain3/C  -I"/Applications/MATLAB_R2017a.app/extern/include" -I"/Applications/MATLAB_R2017a.app/simulink/include" -fno-common -arch x86_64 -mmacosx-version-min=10.9 -fexceptions -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk  -O2 -fwrapv -DNDEBUG /Users/jan.hasenauer/Documents/02_work/05_matlab/LNAplusplus/models/chain3/C/Afunc.c -o /Users/jan.hasenauer/Documents/02_work/05_matlab/LNAplusplus/models/chain3/C/Afunc.o
/Users/jan.hasenauer/Documents/02_work/05_matlab/LNAplusplus/models/chain3/C/Afunc.c:5:10: warning: incompatible pointer types initializing 'double (*)[3][3]' with an expression of type 'double *' [-Wincompatible-pointer-types]
double (*A0)[3][3] = &varOut[0];
         ^           ~~~~~~~~~~
1 warning generated.

/usr/bin/xcrun -sdk macosx10.13 clang -c -DTARGET_API_VERSION=700  -DUSE_MEX_CMD   -DMATLAB_MEX_FILE -Ichain3/C  -I"/Applications/MATLAB_R2017a.app/extern/include" -I"/Applications/MATLAB_R2017a.app/simulink/include" -fno-common -arch x86_64 -mmacosx-version-min=10.9 -fexceptions -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk  -O2 -fwrapv -DNDEBUG /Users/jan.hasenauer/Documents/02_work/05_matlab/LNAplusplus/models/chain3/C/Efunc.c -o /Users/jan.hasenauer/Documents/02_work/05_matlab/LNAplusplus/models/chain3/C/Efunc.o
/Users/jan.hasenauer/Documents/02_work/05_matlab/LNAplusplus/models/chain3/C/Efunc.c:5:10: warning: incompatible pointer types initializing 'double (*)[6][3]' with an expression of type 'double *' [-Wincompatible-pointer-types]
double (*A0)[6][3] = &varOut[0];
         ^           ~~~~~~~~~~
1 warning generated.

**Comment by dweindl** [comment]
This is rather messy, but it's working. Just disabling the warning here for now.
