### ISSUE TITLE
BirthDeath.m tutorial example: Undefined function or variable 'generateLNA'.

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/LNAplusplus#2]
```
>> BirthDeath
Undefined function or variable 'generateLNA'.
```

**Comment by JanHasenauer** [comment]
matlab or python?

**Comment by dweindl** [comment]
matlab. for python it's there.

**Comment by JanHasenauer** [comment]
maybe generateLNAComponents.m?

**Comment by dweindl** [comment]
Tried that one. But it expects additional arguments.

**Comment by dweindl** [comment]
In python generateLNA calls generateLNAComponents, I guess the matlab version of the former is missing.

**Comment by JanHasenauer** [comment]
could be

**Comment by JanHasenauer** [comment]
@feigelman It would be great if you could assist.

**Comment by feigelman** [comment]
Hi Jan,

I will try to take a look as soon as I have time.

Thanks
Justin

**Comment by JanHasenauer** [comment]
Dear Justin,
it would be great if you could have a quick look if you find the file. (The submission deadline is already next week.)
Thanks, Jan

**Comment by JanHasenauer** [comment]
i included the file and some other. I hope that it works now.

**Comment by dweindl** [comment]
Works now, thanks.
